# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ichabod}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex MacCaw"]
  s.date = %q{2011-03-15}
  s.default_executable = %q{ichabod}
  s.email = %q{info@eribium.org}
  s.executables = ["ichabod"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/ichabod",
    "examples/index.html",
    "examples/jasmine/index.html",
    "examples/jasmine/klass.js",
    "examples/jasmine/lib/MIT.LICENSE",
    "examples/jasmine/lib/jasmine-html.js",
    "examples/jasmine/lib/jasmine.css",
    "examples/jasmine/lib/jasmine.js",
    "examples/jasmine/model.js",
    "examples/jasmine/model.spec.js",
    "examples/qunit/index.html",
    "examples/qunit/klass.js",
    "examples/qunit/lib/qunit.css",
    "examples/qunit/lib/qunit.js",
    "examples/qunit/model.js",
    "examples/qunit/model.test.js",
    "ichabod.gemspec",
    "lib/ichabod.rb",
    "lib/ichabod/coercion.rb",
    "lib/ichabod/delegate/load.rb",
    "lib/ichabod/delegate/ui.rb",
    "lib/ichabod/repl.rb",
    "lib/ichabod/runtime.rb",
    "lib/ichabod/script_object/ichabod.rb",
    "lib/ichabod/script_object/ruby.rb",
    "lib/ichabod/tests.rb",
    "lib/ichabod/version.rb",
    "lib/js/jasmine.js",
    "lib/js/qunit.js"
  ]
  s.homepage = %q{http://github.com/maccman/ichabod}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.0}
  s.summary = %q{Ichabod allows headless JavaScript testing using WebKit from the command line.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

